No unbonding when signer or next signer
entropyxyz/entropy-core pull request #1031
Opened 2024-08-26 21:11 UTC by JesseAbram

Related #942

2024-08-28 07:13 UTC, ameba23 approved these changes
+1 This seems like something we need. 

One question i have is how do we force people to use these wrappers and not call the underlying `pallet-staking` extrinsics?  Are they somehow not exposed by our runtime?

Also, if i understand right, validators can anyway only leave at a session change, which is currently when we do a reshare.  So if they call unbond (or chill etc) during a session, could we mark them as being the one who wants to leave the signing committee at the next reshare - or block them from being chosen as a next signer.  That way validators can leave whenever they want.

The argument against this would be that it would make it more complicated to change the frequency of reshares, which i think we will want to do, and there could be complications or security issues if several members of the signing comittee want to unbond in the same session.

2024-08-28 14:56 UTC, JesseAbram commented
> +1 This seems like something we need.
> 
> One question i have is how do we force people to use these wrappers and not call the underlying `pallet-staking` extrinsics? Are they somehow not exposed by our runtime?
> 

That is handled in the base call filter here https://github.com/entropyxyz/entropy-core/pull/1031/files#diff-0ec06ea58bd455f09ce6b3bb4c2c1c0d37bda51c1e1be2151c560c9c973959ecR320-R322


> Also, if i understand right, validators can anyway only leave at a session change, which is currently when we do a reshare. So if they call unbond (or chill etc) during a session, could we mark them as being the one who wants to leave the signing committee at the next reshare - or block them from being chosen as a next signer. That way validators can leave whenever they want.
> 
> The argument against this would be that it would make it more complicated to change the frequency of reshares, which i think we will want to do, and there could be complications or security issues if several members of the signing comittee want to unbond in the same session.

Yes I had this same thought, however this works if one wants to, but if more than one wants to it gets messy, and it isn't like we are locking them in forever, it isn't that long ( a day or two) I think this is worse UX but way simpler, that being said, id say lets do this for now and we can potentially look at and discuss having them pushed out if they want to unbond earlier

2024-08-28 16:32 UTC, HCastano requested changes
Okay, so while the direction of this is correct, the implementation breaks the nominator flow since they can also `chill()`, `unbond()`, etc.

What we need to do here is check if an account is a validator or nominator and act differently depending on the case. See [`chill_stash()`](https://github.com/paritytech/polkadot-sdk/blob/97fa922c85976523f755acdd104fdc77ed63dae9/substrate/frame/staking/src/pallet/impls.rs#L396) from the Staking pallet for example.

2024-08-28 16:32 UTC, HCastano commented on pallets/staking/src/lib.rs
> +        pub fn chill(origin: OriginFor<T>) -> DispatchResultWithPostInfo {
Call it fate, but I was [listening to this](https://soundcloud.com/alexunger/all-i-wanna-do) while reviewing 😆

2024-08-28 16:32 UTC, HCastano commented on pallets/staking/src/lib.rs
> +                    .map_err(|_| Error::<T>::NoThresholdKey)?;
This map contains more than just validator info, it also has nominator info so we may want to change the error here to reflect that

2024-08-28 16:32 UTC, HCastano commented on pallets/staking/src/lib.rs
> +            }
Since we have the `is_some()` check + an `ok_or()` we might be able to get away with an `if let` or some other combinator here

2024-08-28 16:32 UTC, HCastano commented on pallets/staking/src/lib.rs
> +            }
Can probably split this out into its own validation function which is used for the two or three other extrinsics

2024-08-28 16:32 UTC, HCastano commented on pallets/staking/src/tests.rs
Here we should add some tests for the nominator flow

2024-08-28 16:32 UTC, HCastano commented on pallets/staking/src/benchmarking.rs
> +  unbond {
Can you take the body of this (and all the other benches added in this PR) and manually RustFmt it using the [Rust Playground](https://play.rust-lang.org/)? This isn't done by the `fmt` script since it's since a decl macro.

2024-08-28 16:32 UTC, HCastano commented on pallets/staking/src/benchmarking.rs
> +    let c in 0 .. MAX_SIGNERS as u32;
```suggestion
    let s in 0 .. MAX_SIGNERS as u32;
```

2024-08-28 16:32 UTC, HCastano commented
> I did wanna bring up that this breaks convention of staking and maybe if we rename this pallet to staking and mock all the calls in that pallet we can use all the frontends that are built around staking, a little more pallet code but a hella a lot less GUI code.

Oh also, can you elaborate on this? Not sure how renaming and mocking ties into using staking frontends

2024-08-28 16:55 UTC, JesseAbram commented
> > I did wanna bring up that this breaks convention of staking and maybe if we rename this pallet to staking and mock all the calls in that pallet we can use all the frontends that are built around staking, a little more pallet code but a hella a lot less GUI code.
> 
> Oh also, can you elaborate on this? Not sure how renaming and mocking ties into using staking frontends

mocking may not be the write word, wrapping is probably better. Pretty much all staking GUIs would call staking.chill or staking.function. Our code blocks that for the specific calls (chill, unbond........etc) so we can add some extra logic, it would be stakingExtention.function, if we rename staking_extention to staking and staking to idk frame_staking, and wrap all the rest of the calls in that pallet in staking extention, (and keep the same interface) then the GUIs for staking like polkadot js frontend or any other staking wallets should just work, instead of us having to roll our own

2024-08-28 16:58 UTC, JesseAbram commented
> Okay, so while the direction of this is correct, the implementation breaks the nominator flow since they can also `chill()`, `unbond()`, etc.
> 
> What we need to do here is check if an account is a validator or nominator and act differently depending on the case. See [`chill_stash()`](https://github.com/paritytech/polkadot-sdk/blob/97fa922c85976523f755acdd104fdc77ed63dae9/substrate/frame/staking/src/pallet/impls.rs#L396) from the Staking pallet for example.

I think I get it, i think I broke the nominator flow, just to be sure we are on the same page, I still wanna apply the same logic to both however for nominator I need to get who they are nominating and for a validator same flow just get the related stash to the controller

2024-08-28 18:35 UTC, HCastano commented
> mocking may not be the write word, wrapping is probably better. Pretty much all staking GUIs would call staking.chill or staking.function. Our code blocks that for the specific calls (chill, unbond........etc) so we can add some extra logic, it would be stakingExtention.function, if we rename staking_extention to staking and staking to idk frame_staking, and wrap all the rest of the calls in that pallet in staking extention, (and keep the same interface) then the GUIs for staking like polkadot js frontend or any other staking wallets should just work, instead of us having to roll our own

Umm, not sure if it'll be that simple. UIs will probably want to do validation on their
end anyways, and we're emitting different events than the Staking pallet (so the UI might
say something succeeded, but in reality it failed). Something worth following up on though.

> I think I get it, i think I broke the nominator flow, just to be sure we are on the same page, I still wanna apply the same logic to both however for nominator I need to get who they are nominating and for a validator same flow just get the related stash to the controller

For the nominator flow we need to allow a nominator to call `chill()`, `unbond()`, etc.
That's not possible right now since the nominator account would fail the checks that the
`controller` is a signer.

So here we have a couple of options:

1. Skip some of these checks in that case that an an account is a nominator **and** not a validator.
2. If a controller is a nominator, check to see who they're delegaging to. If that person
   is a signer then we don't allow them to perform an action.

I can see (2) being pretty annoying for nominators, but this would help prevent the case
where a validator only puts up a bond of say, `1 UNIT` themselves and then uses a
different nomination account to get reach the required stake.

2024-08-28 21:11 UTC, JesseAbram commented
> > mocking may not be the write word, wrapping is probably better. Pretty much all staking GUIs would call staking.chill or staking.function. Our code blocks that for the specific calls (chill, unbond........etc) so we can add some extra logic, it would be stakingExtention.function, if we rename staking_extention to staking and staking to idk frame_staking, and wrap all the rest of the calls in that pallet in staking extention, (and keep the same interface) then the GUIs for staking like polkadot js frontend or any other staking wallets should just work, instead of us having to roll our own
> 
> Umm, not sure if it'll be that simple. UIs will probably want to do validation on their end anyways, and we're emitting different events than the Staking pallet (so the UI might say something succeeded, but in reality it failed). Something worth following up on though.
> 
> > I think I get it, i think I broke the nominator flow, just to be sure we are on the same page, I still wanna apply the same logic to both however for nominator I need to get who they are nominating and for a validator same flow just get the related stash to the controller
> 
> For the nominator flow we need to allow a nominator to call `chill()`, `unbond()`, etc. That's not possible right now since the nominator account would fail the checks that the `controller` is a signer.

on reading into it, it actually wouldn't but the check won't apply to a nominator which also needs to be fixed. pretty much stash would not apply to who the nominator is validating but their own stash and would fail, however this info is kept in the Nominators storage struct
> 
> So here we have a couple of options:
> 
> 1. Skip some of these checks in that case that an an account is a nominator **and** not a validator.
> 2. If a controller is a nominator, check to see who they're delegaging to. If that person
>    is a signer then we don't allow them to perform an action.
> 
> I can see (2) being pretty annoying for nominators, but this would help prevent the case where a validator only puts up a bond of say, `1 UNIT` themselves and then uses a different nomination account to get reach the required stake.

yes 2 is where I was landing mentally too, you don't need to bond from your validator and it is needed

2024-09-13 18:06 UTC, HCastano reviewed
I still need to look through the benches, but it does look like the nominator flow is working better now

2024-09-13 18:06 UTC, HCastano commented on pallets/staking/src/mock.rs
> +        balances: vec![(1, 100), (2, 100), (3, 100), (4, 100), (7, 100), (8, 100), (101, 200)],
```suggestion
        balances: vec![(1, 100), (2, 100), (3, 100), (4, 100), (7, 100), (8, 100), (9, 100)],
```

For consistency? Or maybe can you explain why you had it as `(101, 200)`?

2024-09-13 18:06 UTC, HCastano commented on pallets/staking/src/lib.rs
> +        pub fn ensure_not_signer_or_next_signer(
This should also mention that it's doing a nominator check

2024-09-13 18:52 UTC, JesseAbram commented on pallets/staking/src/mock.rs
> +        balances: vec![(1, 100), (2, 100), (3, 100), (4, 100), (7, 100), (8, 100), (101, 200)],
nah I just needed a number I knew was not used, 9 probably works

2024-09-16 17:05 UTC, HCastano reviewed
Main thing here is that I think we need to account for nominators in benches now.

Once that and the other review comments are addressed we should be good to go.

2024-09-16 17:05 UTC, HCastano commented on pallets/staking/src/benchmarking.rs
> +  unbond {
This comment is gonna apply to all three of these benches now: we may need to add another parameter, say `let n in 0 .. MaxNominations` ([1]([MaxNominationsOf](https://docs.rs/pallet-staking/37.0.0/pallet_staking/type.MaxNominationsOf.html)) since the `ensure_not_signer_or_next_signer` helper reads the `Nominator` map from storage each time

2024-09-16 17:05 UTC, HCastano commented on CHANGELOG.md
> +- in [#1031](https://github.com/entropyxyz/entropy-core/pull/1031), more Staking calls were blocked to go through staking_extention. This makes sure no funds can be unbonded from a validator if they
```suggestion
- In [#1031](https://github.com/entropyxyz/entropy-core/pull/1031), more Staking calls were blocked
  to go through the `staking_extention` pallet. This makes sure no funds can be unbonded from a
  validator if they are currently in the signing comittee. This was applied to `unbond`, `chill`,
  and `withdraw_unbonded`
```

Wrapping this to 100 characters

2024-09-24 21:18 UTC, HCastano approved these changes

2024-09-27 02:05 UTC, merged