Pregenerate keyshares sets for all possible initial signer comittees
entropyxyz/entropy-core pull request #1073
Opened 2024-09-27 08:22 UTC by ameba23

Closes https://github.com/entropyxyz/entropy-core/issues/1071

Since keyshares are tied to particular party IDs, we cannot give alice's keyshare to bob and expect things to work.

This is an issue now that the initial signer set is chosen randomly - it makes it hard to use the pre-generated keyshares which are already assigned to partiular party IDs (which are TSS account IDs).

One option would be to generate the keyshares at the point when which we know who the signers are.  But this would slow down our tests quite a bit (although since we use a centralized generation it would still be faster than doing a DKG).

So my proposed solution is to pre-generate a set of keyshares for each possible initial signer set.

Since we have 4 nodes, and n=3, we can refer to each set by the name of the node who is **not** in the signer set (which is the one who will act as the relayer node).

So set 'alice' consists of ['bob', 'charlie', 'dave'] and set 'bob' consists of ['alice', 'charlie', dave'], etc.

2024-09-27 08:39 UTC, ameba23 commented on crates/threshold-signature-server/src/helpers/launch.rs
> +        write!(f, "{}", format!("{:?}", self).to_lowercase())
This is used for putting the validator names in filepaths - we just take the validator name as lower case

2024-09-27 10:15 UTC, ameba23 commented on crates/threshold-signature-server/src/helpers/tests.rs
> +        panic!("No non signer");
I guess since we panic here, it does not make sense to return an option - as the option will always be `Some`. The alternative would be to not panic and just not put any keyshares. :shrug:

2024-09-27 13:38 UTC, JesseAbram requested changes
looks good just definitely needs a good readme with how to run and why etc etc

2024-09-27 13:38 UTC, JesseAbram commented on crates/threshold-signature-server/src/helpers/tests.rs
> +        panic!("No non signer");
can we just ignore it and return none?

2024-09-30 20:18 UTC, HCastano approved these changes
Something I'd want to look into in the future is not having 50 build artifacts as part of the repo - so maybe generating these once either at build-time or test-build-time. 

I'm thinking that its a similar thing to a lockfile. These can be generated so they don't necessarily need to be version controlled in all cases.

2024-09-30 20:18 UTC, HCastano commented on crates/threshold-signature-server/src/helpers/tests.rs
> +        tracing::error!("No non signer - not storing pre-generated keyshares");
```suggestion
        tracing::error!("Missing non-signer - not storing pre-generated keyshares");
```

2024-09-30 20:18 UTC, HCastano commented on scripts/create-test-keyshares/src/main.rs
> +        // We cant do .try_into().unwrap() here becasue sr25519::Pair doesn't implement Debug
We can map the error to something that does, e.g `.map_err(|_| ())`

2024-10-01 06:54 UTC, ameba23 commented on scripts/create-test-keyshares/src/main.rs
> +        // We cant do .try_into().unwrap() here becasue sr25519::Pair doesn't implement Debug
Like it, thanks!

2024-10-01 07:00 UTC, ameba23 commented
@JesseAbram i can't merge this until you re-review

2024-10-01 13:04 UTC, JesseAbram approved these changes

2024-10-01 16:05 UTC, merged