Create local large testnet
entropyxyz/entropy-core pull request #902
Opened 2024-06-21 18:52 UTC by JesseAbram

This creates a local docker large testnet with 4 validators as discussed here

https://github.com/entropyxyz/sdk/pull/383

2024-06-21 19:04 UTC, JesseAbram commented
> Thanks so much for putting this together. It's also helpful to have an example of what needs to change in order to produce a new chain spec like this. I have one small question, commented inline.

ya no worries lol but will only be helpful for like mmmmm a few weeks

2024-06-21 19:34 UTC, HCastano requested changes
Main change needed here is that this should be part of the `dev` chainspecs, not the `testnet` ones.

2024-06-21 19:34 UTC, HCastano commented on crates/threshold-signature-server/src/helpers/launch.rs
> +    pub eve: bool,
We might as well add `--charlie` here too

2024-06-21 19:34 UTC, HCastano commented on node/cli/src/chain_spec/mod.rs
> +    pub const DAVE: [u8; 32] = [
Now that this is available, can you also update this line?

https://github.com/entropyxyz/entropy-core/blob/3cbc794f97cbcc0f92cc27363f744a6529b82294/node/cli/src/chain_spec/integration_tests.rs#L178

2024-06-21 19:34 UTC, HCastano commented on node/cli/src/chain_spec/testnet.rs
> +        crate::chain_spec::authority_keys_from_seed("Eve"),
Why is `Charlie` being skipped?

2024-06-21 19:34 UTC, HCastano commented on node/cli/src/chain_spec/testnet.rs
This config should actually be added to the `dev` chain spec, not the testnet one. So we should end up with `devnet-local-large` instead.

2024-06-21 19:34 UTC, HCastano commented on node/cli/src/command.rs
> +            "testnet-local-large" => Box::new(chain_spec::testnet::testnet_local_config_large()),
I would be more specific here: `devnet-local-four-nodes`

2024-06-21 19:37 UTC, JesseAbram commented on node/cli/src/chain_spec/testnet.rs
> +        crate::chain_spec::authority_keys_from_seed("Eve"),
I am following this docker script https://github.com/entropyxyz/sdk/pull/383/files which selects alice bob dave eve

2024-06-21 19:37 UTC, JesseAbram commented on node/cli/src/chain_spec/testnet.rs
probably the same for testnet-local then (the two node docker script, I kinda just copied off that)

2024-06-21 19:41 UTC, HCastano commented on node/cli/src/chain_spec/testnet.rs
The `testnet-local` config was added intentionally to allow for a lightweight way to check the testnet configuration. We should keep that where it is.

2024-06-21 19:41 UTC, HCastano commented on node/cli/src/chain_spec/testnet.rs
> +        crate::chain_spec::authority_keys_from_seed("Eve"),
There's gotta be a deeper reason though, no?

2024-06-21 19:43 UTC, JesseAbram commented on node/cli/src/chain_spec/testnet.rs
> +        crate::chain_spec::authority_keys_from_seed("Eve"),
you can compare notes with my therapist? but no, I just was working off the docker script @vitropy created

2024-06-21 19:48 UTC, JesseAbram commented on node/cli/src/chain_spec/testnet.rs
actually looking at it the dev stuff has a lot of things in there we need for testing, this is meant to function as a testnet with items we do not need, much like the testnet-local, I don't think this makes sense to move it

2024-06-24 16:03 UTC, HCastano commented on node/cli/src/chain_spec/testnet.rs
@JesseAbram The reason I'm saying that this should be a `dev` spec is that the current SDK testing setup uses a 
[two node](https://github.com/entropyxyz/sdk/blob/main/dev/docker-scripts/two-nodes.yaml) `dev` spec.

By changing this to a testnet config it could introduce unintended differences into their
testing environment.

So unless the SDK team (@entropyxyz/js-devs) explicit asked for this and/or is okay with this, then I would
suggest moving it.

2024-06-24 16:06 UTC, HCastano commented on node/cli/src/chain_spec/integration_tests.rs
>                          // is unavailable right now.
Thanks for updating the key, do you mind removing this comment now?

2024-06-24 16:06 UTC, HCastano commented on node/cli/src/chain_spec/testnet.rs
> +        .with_id("entropy_testnet_local_large")
This should be changed to "*-four-nodes"

2024-06-24 17:13 UTC, JesseAbram commented on node/cli/src/chain_spec/testnet.rs
ahhh I see ok will have to update a lot in devnet config but should be fine

2024-06-24 19:21 UTC, HCastano approved these changes
FYI Jesse I pushed up some changes.

I tested that the chainspecs are still building by running:

```
 cargo run -p entropy -- build-spec --raw --chain devnet-local > chainspec-dev-raw.json
cargo run -p entropy -- build-spec --raw --chain devnet-local-four-nodes > chainspec-dev-four-nodes-raw.json
```

I haven't actually ran the four node Compose network though.

2024-06-25 15:30 UTC, merged